### ISSUE TITLE
Improve error messages when interacting with data sets

### ISSUE THREAD

**Issue by DinoV** [Azure/Azure-MachineLearning-ClientLibrary-Python#23] opened 2015-11-30 14:30 UTC
Error message in Ipython Notebook is not clear enough. Right now, the error message from azureml package is not clear to me. For example, if I push two datasets with the same name to AML, there would be a conflict of datasets. But the error message is “AzureMLConflictHttpError: Request ID: 9a59338a-e27b-4d9d-a20b-ec4ceb6d6fc8 2015-11-15 20:15:42Z”, which is not very clear to me.

**Comment by andrie** [comment] 2015-11-30 14:58
This repo is no longer in use.  Please post any comments at https://github.com/RevolutionAnalytics/AzureML/issues

---

PS. This issue is known, and a duplicate of https://github.com/RevolutionAnalytics/AzureML/issues/62

**Comment by DinoV** [comment] 2015-11-30 15:22
This is the Python repo and I do believe it's still in use, at least I don't see any Python code over in the R repo ;)

**Closed** 2015-12-01 14:21 UTC
